# Generated by Django 3.2 on 2021-06-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.IntegerField(verbose_name='Dni/Ruc')),
                ('vendor', models.CharField(max_length=150, verbose_name='Vendedor')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('address', models.CharField(max_length=200, verbose_name='Direccion')),
                ('district', models.CharField(max_length=100, verbose_name='Distrito')),
                ('refference', models.CharField(max_length=150, verbose_name='Referencia')),
                ('phone', models.IntegerField(verbose_name='Telefono')),
                ('mail', models.CharField(max_length=150, verbose_name='Correo electronico')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('priority', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='Prioridad')),
                ('service', models.CharField(choices=[('Tv', 'Tv'), ('Internet', 'Internet'), ('Ambos', 'Ambos')], max_length=10, verbose_name='Servicios')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('install_date', models.DateField(verbose_name='Fecha de instalacion')),
                ('materials', models.TextField(verbose_name='Materiales')),
                ('price', models.FloatField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Formulario de venta',
                'verbose_name_plural': 'Formularios de ventas',
            },
        ),
    ]
