# Generated by Django 3.2 on 2021-06-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='company',
            field=models.BooleanField(default=True, verbose_name='Es una empresa'),
            preserve_default=False,
        ),
    ]
