# Generated by Django 3.2 on 2021-07-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Telefono'),
        ),
    ]
