# Generated by Django 3.2 on 2021-06-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finanzas', '0002_sales_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='company',
            field=models.BooleanField(default=True, verbose_name='Es una empresa'),
        ),
    ]
