# Generated by Django 3.2 on 2021-07-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finanzas', '0002_alter_sales_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='install_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de instalacion'),
        ),
    ]
