# Generated by Django 3.2 on 2021-09-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finanzas', '0003_alter_sales_install_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Temporal', 'Corte temporal'), ('Mora', 'Corte por mora'), ('Cancelacion', 'Corte por cancelacion del contrato')], max_length=20, verbose_name='Status del servicio'),
        ),
    ]
