# Generated by Django 3.2 on 2021-06-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finanzas', '0003_alter_sales_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='company',
            field=models.BooleanField(default=False, verbose_name='Es una empresa'),
        ),
    ]
