# Generated by Django 3.2 on 2021-06-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finanzas', '0004_alter_sales_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='document',
            field=models.IntegerField(unique=True, verbose_name='Dni/Ruc'),
        ),
    ]
