# Generated by Django 3.2 on 2021-09-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finanzas', '0004_sales_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='toPay',
            field=models.FloatField(blank=True, default=200, verbose_name='Monto a pagar'),
            preserve_default=False,
        ),
    ]
