# Generated by Django 3.2 on 2021-09-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finanzas', '0007_alter_sales_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='department',
            field=models.CharField(default=12, max_length=100, verbose_name='Departamento al que perteneceS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='ip',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Cantidad de ip'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='toPay',
            field=models.FloatField(default=12, verbose_name='Monto a pagar'),
            preserve_default=False,
        ),
    ]
